name: ramp-coral
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - statsmodels
  - matplotlib
  - seaborn
  - missingno
  - scikit-learn>=0.22

  - pip
  - pip:
    - ramp-workflow==0.6.0
